backend = "glx";
vsync = true;

corner-radius = 10;
rounded-corners-exclude = [
  "class_g = 'i3-frame'"
];

blur = {
  method = "dual_kawase";
  strength = 7;
  background = true;
  background-frame = true;
  background-fixed = false;
};

blur-background-exclude = [
  "class_g != 'kitty'",
  "name = 'Picture in picture'"
];

opacity-rule = [
  "90:class_g = 'kitty'",
  "100:name = 'Picture in picture'"
];

shadow = true;
shadow-radius = 12;
shadow-offset-x = -10;
shadow-offset-y = -10;
shadow-opacity = 0.6;

shadow-exclude = [
  "class_g = 'i3-frame'",
  "class_g = 'Conky'",
  "name = 'Notification'",
  "class_g = 'polybar'",
  "class_g ?= 'rofi'",
  "name = 'Picture in picture'",
  "_GTK_FRAME_EXTENTS@:c"
];

fading = true;
fade-delta = 4;
fade-in-step = 0.03;
fade-out-step = 0.03;
